export const GET_ALL_PRODUCTS_MAKE_API_REQUEST = 'GET_ALL_PRODUCTS_MAKE_API_REQUEST';
export const GET_ALL_PRODUCTS_REQUEST_SUCCESS = 'GET_ALL_PRODUCTS_REQUEST_SUCCESS';
export const GET_ALL_PRODUCTS_REQUEST_FAILURE = 'GET_ALL_PRODUCTS_REQUEST_FAILURE';
